
export const USER_SIGNIN = 'USER_SIGNIN';

export const NEWS_DATA = 'NEWS_DATA';
export const NEWS_DATA_SUCCESS = 'NEWS_DATA_SUCCESS';
export const NEWS_DATA_FAILED = 'NEWS_DATA_FAILED';

export const CATEGORY_NEWS_DATA = 'CATEGORY_NEWS_DATA';
export const CATEGORY_NEWS_DATA_SUCCESS = 'CATEGORY_NEWS_DATA_SUCCESS';
export const CATEGORY_NEWS_DATA_FAILED = 'CATEGORY_NEWS_DATA_FAILED';
